### ISSUE TITLE
Plugin should do a limited rescan when changing sample rate

### ISSUE THREAD

**Issue by aacuevas** [open-ephys-plugins/rhythm-oni-plugin#14]
The way it works now, when doing a port scan (at the plugin constructor or when clicking the scan ports button), the plugin temporarily sets the sample rate to 30KS/s, does a full scan on all the ports with delays from 0 to 15 to retrieve connected headstages and their delays and then saves those delays as  a "cable length" value using an equation on the Intan API. When changing sample rate, the plugin takes this length value and transforms it into a new delay (which is dependent on sampling rate) using a reverse equation, also in the API.

Due to rounding errors, this conversion is not exact, the lower the sampling rate, the bigger the error. This causes that, for low sampling rates, an invalid delay is set, resulting in corrupt headstage data. Thus, an actual port scan should be performed when changing sample rates to get actual delays.

Actual delays for lower sample rates are close to the reference one measured at 30KS/s (let's call it N) and lower than it, so this reference value should be saved and this scan could be a limited scan, at the desired sample rate, but between N-2 and N (some further empirical tweaking might be needed to this range, but current measures support it). Also, this limited scan should not have to disable or enable streams, as the plugin already knows which headstages are plugged, just do a quick, fast, limited scan to get the good delays for the selected sample rate.

**Comment by jsiegle** [comment]
Just pushed the relevant changes to this branch: https://github.com/open-ephys-plugins/rhythm-oni-plugin/tree/smarter-scans

Can you let me know if this looks reasonable?

**Comment by aacuevas** [comment]
Mostly yes,
 The only thing is in the blocks like https://github.com/open-ephys-plugins/rhythm-oni-plugin/blob/fdff3965d17c34a0bdba8872e1464ef72fa57a29/Source/DeviceThread.cpp#L1540
You are overwritting the stored delay when changing sampling rates. The stored delay should be always the one at 30KS/s done by the port scan, this mini-scan always using that value as the base and just set the offsetted delay to the board.

Also, I'd remove all references to anything "CableLengthMeters" related, those are unneeded now and could cause issues.

And as a minor comment https://github.com/open-ephys-plugins/rhythm-oni-plugin/blob/fdff3965d17c34a0bdba8872e1464ef72fa57a29/Source/DeviceThread.cpp#L1456 Should be from -2 to 1 though.

If you could please handle these changes, I'll then test on my hardware. Thanks!

**Comment by jsiegle** [comment]
Ok, just pushed those changes. Let me know if it works on your end!

**Comment by aacuevas** [comment]
I had to fix a couple bugs but seems to work now!
I have also updated the library DLLs for a bit better performance, so they can be merged together with this branch for next plugin version.

**Comment by jsiegle** [comment]
Ok! Let us know when those changes are up and we can put out a new release.

**Comment by aacuevas** [comment]
Sorry! I committed them but forgot to push them!

Should be on the branch now

**Comment by jsiegle** [comment]
Great! @anjaldoshi can you put out a new release?

**Comment by anjaldoshi** [comment]
New release (v0.2.4) is up!
