### ISSUE TITLE
Ensure plugin launches when board is unplugged

### ISSUE THREAD

**Issue by jsiegle** [open-ephys-plugins/rhythm-oni-plugin#20]
See https://github.com/open-ephys/plugin-GUI/issues/611

**Comment by ChucklesOnGitHub** [comment]
FYI This was happening for us in the GUI version 0.6.7, plugin version 0.2.6. I am using v0.6.6 and plugin v0.2.3 on another computer and have no issues using the OE Acquisition Board source processor in the signal chain without the board being connected.

**Comment by anjaldoshi** [comment]
Just adding to this. It is most likely happening due to a combination of the plugin and ONI/FTDI driver version.  If you look at crash log attached in the original issue, the last call in the stack trace was `oni_write_frame`.

**Comment by jsiegle** [comment]
I was able to replicate this, and pushed a fix to the `testing` branch of the `rhythm-oni-plugin` repo. It was indeed related to checking the FTDI driver version – I just changed it so this only happens if the board is connected.
