### ISSUE TITLE
Can we add an output to console when the OE FPGA Acquisition Board is not detected?

### ISSUE THREAD

**Issue by ChucklesOnGitHub** [open-ephys-plugins/rhythm-oni-plugin#21]
Afaik, if you drag the source processor or load a config which has the OE FPGA Acquisition Board plugin but don't have the board connected, the pop-up comes up saying "Acquisition Board not found".
![image](https://github.com/open-ephys-plugins/rhythm-oni-plugin/assets/16124331/3478f484-6c1c-45af-8f86-9c4096f6e708)

The console however, only shows that the source processor was created, or that the signal chain was loaded.
![image](https://github.com/open-ephys-plugins/rhythm-oni-plugin/assets/16124331/8bb6639e-b63c-4492-8297-d5811c38f0e2)

Can we have a text saying that no board was found in the console log for troubleshooting purposes?

The Opal Kelly version has this one:
![image](https://github.com/open-ephys-plugins/rhythm-oni-plugin/assets/16124331/af981f8c-1327-4660-a57c-91f85f583b33)

**Comment by jsiegle** [comment]
This is what it looks like with the latest changes:

![image](https://github.com/open-ephys-plugins/rhythm-oni-plugin/assets/200366/f68e9db0-611d-4989-bbe9-ff6ca4d91db8)

We will put out a new release soon!
