### ISSUE TITLE
Assertion in debug when saving xml

### ISSUE THREAD

**Issue by aacuevas** [open-ephys-plugins/rhythm-oni-plugin#4]
It seems the xml writer does not like the name, probably due to the parenthesis, and asserts a "is valid xml" function. This does not happen on release, but might cause issues with signal chain loading. Can you look into this and see if it's worth changing the name @anjaldoshi or @jsiegle  ? thanks!

**Comment by jsiegle** [comment]
This actually does create problems when the [plugin name is converted to an XML tag](https://github.com/open-ephys/plugin-GUI/blob/b28c1bde94fbabcc92ab7c2222496643ee6abdf8/Source/UI/EditorViewport.cpp#L1465) -- this corrupts the settings file such that it can no longer be loaded. I added some code to prevent this on the `development` branch, but I think it's still worth changing the name. So I switched the parentheses to a hypen.

@anjaldoshi can you merge `dev` into `main` and put out a new release (v0.1.2)?

**Comment by anjaldoshi** [comment]
Done! You may have to manually uninstall any older version of the plugin before installing the latest version via Plugin Installer.
